### PR TITLE
268/make contact lean form

### PR DESCRIPTION
**Pull request by sebgrebe**
- Created new routes /contact-lean, /contact-tech, /contact-success
- Using zapier.com, data entered in forms is sent to an email address (currently sebbecker@gmx.net)
- In production, this should be sent to lean@eahub.org and tech@rtcharity.org. The email addresses data is sent to can be changed [here](https://zapier.com/app/dashboard). Password and username for zapier.com is on lastpass.
- Changed the links on about page from emails to the contact pages.
- PROBLEM: Zapier only gives 100 "tasks" per month for free, i.e., only 100 messages could be sent via the contact form. I will get an alert if we get close to our limit, in which case we could change back to emails (not ideal).

### CODE REVIEW

**Comment by taymonbeal** [comment]
Netlify comes with a Forms feature with the same free quota as Zapier. I think it'd be preferable to use that to reduce the complexity associated with using many different services.

If we exceed the free quota, it's also possible to self-host this with Netlify Functions and Mailgun, which we can do with a much more generous free tier, at the cost of added technical complexity. Or we could just pay $20 per month.

**Comment by sebgrebe** [comment]
@taymonbeal Thanks for your comments! I agree, doing it with netlify would be better.
@michaltrzesimiech 
1) Would you like me to implement the form with netlify now? We could then later rebuild it with the Django app, to circumvent the restriction to 100 emails? 
2) Should we delay implementing the form, stick with the mailto@ solution for the moment and only implement the form once we have the Django app? I'd prefer this in case you expect we'll get > 100 messages/month.

**Comment by taymonbeal** [comment]
If we think we're going to want the form _eventually_, then there's no need to delay. Getting at least a simple setup in place is not much wasted effort, and changing to a different backend should not even be noticed by users.

The only exception is if you'd rather not have a form than pay $20 if you go over the free tier, and you think that's likely to happen. Personally I'm fine with paying $20 and I think we're unlikely to go over.

**Comment by sebgrebe** [comment]
I’ve implemented this now with netlify (LEAN contact: https://confident-minsky-f713d6.netlify.com/contact-lean/, Tech contact: https://confident-minsky-f713d6.netlify.com/contact-tech/). The links go to a test page, so it’s not live yet.

On filling out a contact form, the user needs to do one of those “prove you’re human captchas”. Feel free to click submit on the form, but don't go past the captcha, as this goes off our quota.

Let's go with the free plan for now. As it does not automatically go to pro (I did not add a credit card to our account), it's risk-free. If we should hit the quota, we might have to take you up on your offer, @taymonbeal  :)

Currently waiting on the final OK from @Richenda and @michaltrzesimiech, will then make it live.

**Comment by taymonbeal** [comment]
form.js shouldn't be needed anymore, should it?

**Comment by sebgrebe** [comment]
> form.js shouldn't be needed anymore, should it?

good catch, thanks. Deleted.
BTW, Code for this is now on [this](https://github.com/rtcharity/resources.eahub.org/tree/test) branch, which is linked to the test page.

**Pull request merged**
